name: google_visualization_api
version: 0.0.1
author: Robert Hartung <robert.w.hartung@gmail.com>
description: A Dart (wrapper) package to access Google's Visualization API.
homepage: https://github.com/roberthartung/google_visualization_api
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  polymer: any
dev_dependencies:
  html: any
  http: any
transformers:
- polymer:
    entry_points:
    - example/polymer/table.html
    - example/polymer/donutchart.html
