name: google_charts
version: 0.1.3+2
author: Robert Hartung <robert.w.hartung@gmail.com>
description: Google Charts API Wrapper Classes.
homepage: https://github.com/roberthartung/google_charts
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  polymer: ^1.0.0-rc.2
  web_components: ^0.12.0
  reflectable: "^0.3.1"
dev_dependencies:
  html: any
  http: any
transformers:
- web_components:
    entry_points:
    - example/polymer/donutchart/index.html
    - example/polymer/table/index.html
- reflectable:
    entry_points:
    - example/polymer/donutchart/index.dart
    - example/polymer/table/index.dart
